In [4]:
####
from selenium import webdriver
from selenium.webdriver.chrome.options import Options  ## for headless mode
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
#######
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
import re 
from matplotlib import pyplot as plt
import seaborn as sns
import urllib3
pd.plotting.register_matplotlib_converters()
from warnings import filterwarnings
filterwarnings('ignore')
# %matplotlib inline
import time
print("Setup Complete")

Setup Complete

### function

In [7]:
def scraper(url_of_page):
    num=[]
    df=pd.DataFrame()
    http = urllib3.PoolManager()
    l = http.request('GET',url_of_page)
    soup_1=BeautifulSoup(l.data, 'html.parser')
    links_1 = soup_1.findAll('a', class_='phone')
    for i in range (len(links_1)):
        number=re.sub('<[^>]+>' , ' ', str(links_1)).strip().replace(' (','').replace('[','').replace(']','').replace(') ','').replace('-','').split(',')[0].strip()
        num.append({'link':url_of_page,'number':number})
    df=pd.DataFrame(num)
    # df.to_excel('output1.xlsx', engine='xlsxwriter')
    return df

In [12]:
scraper('https://turbo.az/autos/6735686-hyundai-sonata')

                                            link      number
0  https://turbo.az/autos/6735686-hyundai-sonata  0703055599

## personal auto

In [33]:
%%time
links_personal_auto=[]
num=[]
df=pd.DataFrame()
for x in range(1,2):
    url=f'https://turbo.az/autos?page={x}'
    request=requests.get(url).content
    soup=BeautifulSoup(request,'html.parser')
    cars=soup.find_all('div',class_='products-i')
    for i in cars:
        links_personal_auto.append('https://turbo.az'+i.a['href'])      
    for i in range (len(links_personal_auto)):
        http = urllib3.PoolManager()
        content = http.request('GET',links_personal_auto[i])
        soup_1=BeautifulSoup(content.data, 'html.parser')
        try:
            links_1 = soup_1.findAll('div',class_="seller-name")
            
            name=re.sub('<[^>]+>' , ' ', str(links_1)).strip().replace(' (','').replace('[ ','').replace(' ]','').replace(') ','').replace('-','').split(',')[0].strip()
            
        except:
            
            name='null'
       
        try:
            
            links_2 = soup_1.findAll('a', class_='phone')
            
            number=int(re.sub('<[^>]+>' , ' ', str(links_2)).strip().replace(' (','').replace('[','').replace(']','').replace(') ','').replace('-','').split(',')[0].strip())
            
        except :
        
            number=0
        try:
            
            links_3 = soup_1.findAll('h1', class_='product-name product-name-row')
            
            automobile=re.sub('<[^>]+>' , ' ', str(links_3)).strip().replace(' (','').replace('[ ','').replace(' ]','').replace(') ','').replace('-','').split(',')[0].strip()
            
        except:
            
            automobile='null'
        try:
            
            links_4 = soup_1.findAll('div', class_='product-price')
            
            price=re.sub('<[^>]+>' , ' ', str(links_4)).strip().replace(' (','').replace('[ ','').replace(' ]','').replace(') ','').replace('-','').split(',')[0].strip()
            
        except:
            
            price='null'
            
        try:
            
            links_5 = soup_1.findAll('div', class_='product-properties-value')
            
            city=re.sub('<[^>]+>' , ' ', str(links_5)).strip().replace(' (','').replace('[ ','').replace(' ]','').replace(') ','').replace('-','').split(',')[0]
            
        except:
            
            city='null'
            
        num.append({'url':links_personal_auto[i],'name':name,'number':number,'automobile':automobile,'price':price,'city':city})

    df=pd.DataFrame(num)        
df

CPU times: total: 2.22 s
Wall time: 34 s

,url,name,number,automobile,price,city
0,https://turbo.az/autos/6683500-lexus-lx-500d,[],0,[],173 000 $,Bakı
1,https://turbo.az/autos/6332758-honda-cr-v,[],0,[],40 900 $,Bakı
2,https://turbo.az/autos/6716492-bmw-x5,[],0,[],49 800 $,Bakı
3,https://turbo.az/autos/6195122-subaru-forester,[],0,[],40 900 $,Bakı
4,https://turbo.az/autos/6725273-land-rover-rr-v...,Farid,702501151,Land Rover RR Velar,68 800 $,Bakı
5,https://turbo.az/autos/6485583-land-rover-disc...,Fuad,519077777,Land Rover Discovery,39 500 $,Bakı
6,https://turbo.az/autos/6658911-hyundai-veracruz,El Shahin,708656560,Hyundai Veracruz,20 800 AZN,Bakı
7,https://turbo.az/autos/6458026-bmw-x6,Fuad,502052025,BMW X6,62 000 $,Bakı
8,https://turbo.az/autos/6714796-hyundai-santa-fe,Elçin,555098888,Hyundai Santa Fe,23 300 AZN,Bakı
9,https://turbo.az/autos/6681255-toyota-prado,Elçin,555999905,Toyota Prado,29 900 AZN,Bakı
10,https://turbo.az/autos/6573322-land-rover-disc...,Samir,502888252,Land Rover Discovery,43 500 $,Bakı
11,https://turbo.az/autos/6496763-land-rover-rr-s...,Elcin,502118126,Land Rover RR Sport,59 000 $,Bakı
12,https://turbo.az/autos/6698643-ford-fusion,[],0,[],22 500 AZN,Bakı
13,https://turbo.az/autos/6678202-jeep-grand-cher...,Sampat,502842016,Jeep Grand Cherokee,22 500 $,Bakı
14,https://turbo.az/autos/6736026-lada-vaz-2106,Rizvan,517331205,LADAVAZ2106,6 500 AZN,Bakı
15,https://turbo.az/autos/6736029-mercedes-190,Ağamoğlan,774370028,Mercedes 190,6 700 AZN,Bakı
16,https://turbo.az/autos/6733872-bmw-x5,Farid,555557978,BMW X5,51 500 $,Bakı
17,https://turbo.az/autos/6698600-chevrolet-captiva,[],0,[],16 800 AZN,Bakı
18,https://turbo.az/autos/6669342-hyundai-matrix,Rustam,506557627,Hyundai Matrix,11 900 AZN,Bakı
19,https://turbo.az/autos/6723234-lada-vaz-priora,[],0,[],10 500 AZN,Sumqayıt
20,https://turbo.az/autos/6718368-land-rover-disc...,Elvin,502444004,Land Rover Discovery Sport,33 000 $,Bakı
21,https://turbo.az/autos/6588661-hyundai-sonata,[],0,[],54 900 AZN,Bakı
22,https://turbo.az/autos/6717349-mercedes-viano,[],0,[],22 800 AZN,Bakı
23,https://turbo.az/autos/6736027-mondial-100-loyal,Asiman,709096062,Mondial 100 Loyal,1 300 AZN,Qusar
24,https://turbo.az/autos/6699945-chevrolet-cruze,[],0,[],17 500 AZN,Bakı
25,https://turbo.az/autos/6712145-kia-sorento,Ramin,502744644,Kia Sorento,33 800 AZN,Bakı
26,https://turbo.az/autos/6692793-infiniti-fx35,[],0,[],18 300 AZN,Bakı
27,https://turbo.az/autos/6716374-honda-insight,Yusif,552047101,Honda Insight,15 300 AZN,Bakı
28,https://turbo.az/autos/6736024-toyota-prius,Mehi,703131319,Toyota Prius,10 900 AZN,Bakı
29,https://turbo.az/autos/6717321-honda-cr-v,[],0,[],10 800 AZN,Bakı
30,https://turbo.az/autos/6736021-hyundai-tucson,[],0,[],53 200 AZN,Bakı
31,https://turbo.az/autos/6579560-hyundai-tucson,[],0,[],59 900 AZN,Bakı
32,https://turbo.az/autos/6736022-toyota-corolla,[],0,[],14 300 AZN,Sumqayıt
33,https://turbo.az/autos/6679737-toyota-prado,Kanan,518007766,Toyota Prado,33 900 AZN,Bakı
34,https://turbo.az/autos/6588632-hyundai-grandeur,[],0,[],74 500 AZN,Bakı
35,https://turbo.az/autos/6721426-kia-optima,[],0,[],22 900 AZN,Sumqayıt

In [14]:
df.to_excel('personal_numbers.xlsx', engine='xlsxwriter')

## salon autos

In [5]:
%%time
links_salon_auto=[]
num=[]
salon_number=pd.DataFrame()
http = urllib3.PoolManager()

for x in range(1,5):
    url=f'https://turbo.az/autos?page={x}'
    request=requests.get(url).content
    soup=BeautifulSoup(request,'html.parser')
    cars=soup.find_all('div',class_='products-i salon')

    for i in cars:
        links_salon_auto.append('https://turbo.az'+i.a['href'])
        
    for i in range (len(links_salon_auto)):
        content = http.request('GET',links_salon_auto[i])
        soup_1=BeautifulSoup(content.data, 'html.parser')
        try:
            links_1 = soup_1.findAll('div', class_='shop-contact--phones-i')
            number=int(re.sub('<[^>]+>' , ' ', str(links_1)).strip().replace(' (','').replace('[','').replace(']','').replace(') ','').replace('-','').split(',')[0].strip())
            num.append({'number':number})
        except ValueError:
            number=0
    salon_number=pd.DataFrame(num)        
salon_number.tail(5)

CPU times: total: 1.47 s
Wall time: 13.5 s

       number
12  998910021
13  552152626
14  773866685
15  773866685
16  503383436

In [18]:
sal.to_excel('salon_numbers.xlsx', engine='xlsxwriter')